# SPDX-License-Identifier: GPL-2.0

# We only ever need to build luckfox dtbs for this kernel.
dtb-$(CONFIG_ARCH_ROCKCHIP) += \
	rk3506g-luckfox-lyra.dtb \
	rk3506g-luckfox-lyra-plus.dtb \
	rk3506b-luckfox-lyra-ultra.dtb \
	rk3506b-luckfox-lyra-ultra-w.dtb \
	rk3506b-luckfox-lyra-zero-w.dtb \
	rk3506b-luckfox-lyra-pi.dtb \
	rk3506b-luckfox-lyra-pi-w.dtb \
	rk3506b-luckfox-lyra-pi-sd.dtb \
	rk3506b-luckfox-lyra-pi-w-sd.dtb
