import datetime
import shutil
import subprocess
import sys

from .devicetree import DeviceTree
from .sources import DtsoRule


class Build:
    _CONFIG_INSTALL_HEADER = f"""
    THIS FILE IS GENERATED. ({datetime.datetime.now().isoformat()})

    If you wish to edit this file, use the lyra-overlays tool.
    """

    _CONFIG_BACKUP_HEADER = f"""
    THIS FILE IS GENERATED. ({datetime.datetime.now().isoformat()})

    This file is a backup of the file used to generate the overlays in
    this directory. Editing it will not do anything. Instead, use the
    lyra-overlays tool.
    """

    _OUTPUT_README = f"""
    THIS DIRECTORY IS GENERATED ({datetime.datetime.now().isoformat()})

    The overlays in this directory are generated by lyra-overlays. If
    you modify these files directly, those changes may be lost the
    next time lyra-overlays is run.
    """

    _RMIO = [
        # 0
        'GPIO0_A0', 'GPIO0_A1', 'GPIO0_A2', 'GPIO0_A3',
        'GPIO0_A4', 'GPIO0_A5', 'GPIO0_A6', 'GPIO0_A7',
        # 8
        'GPIO0_B0', 'GPIO0_B1', 'GPIO0_B2', 'GPIO0_B3',
        'GPIO0_B4', 'GPIO0_B5', 'GPIO0_B6', 'GPIO0_B7',
        # 16
        'GPIO0_C0', 'GPIO0_C1', 'GPIO0_C2', 'GPIO0_C3',
        'GPIO0_C4', 'GPIO0_C5', 'GPIO0_C6', 'GPIO0_C7',
        # 24
        'GPIO1_B1', 'GPIO1_B2', 'GPIO1_B3', 'GPIO1_C2',
        'GPIO1_C3', 'GPIO1_D1', 'GPIO1_D2', 'GPIO1_D3',
    ]

    def __init__(self, path, src, cfg, out, dt):
        self._path = path
        self._src = src
        self._cfg = cfg
        self._out = out
        self._dt = dt

        uname = subprocess.run(['uname', '-r'],
                               check=True, capture_output=True)
        uname = uname.stdout.decode('utf-8').strip()
        self._cpp_flags = [
            '-nostdinc', '-undef', '-x', 'assembler-with-cpp',
            '-I', '/usr/src/linux-headers-' + uname + '/include/',
            '-I', self._src.include,
            '-I', self._path,
        ]

        self._local_cfg = path / 'lyra-overlays.config'
        self._local_h = path / 'config.h'
        self._local_check = path / 'lyra-overlays-check.dtb'
        self._backup_cfg = self._out.path / 'lyra-overlays.config.bak'
        self._output_readme = self._out.path / 'README'

        if self._cfg.exists():
            self._src.olddefconfig(self._cfg.path, self._local_cfg)
        else:
            with open(self._local_cfg, 'w') as f:
                f.write(self._cfg.generate_default())

        self._cfg_updated = False
        self._build_updated = False

    def _log(self, typ, line):
        print(f'  {typ.upper():7s} {line}')

    def configure(self):
        self._src.menuconfig(self._local_cfg)
        self._cfg_updated = True

    def clean(self):
        for p in self._path.glob('*.dtbo'):
            self._log('rm', p.name)
            p.unlink()

    def build(self):
        self._src.genconfig(self._local_cfg, self._local_h)

        for rule in self._src.get_active_rules(self._local_cfg):
            if isinstance(rule, DtsoRule):
                self._build_dtso(rule)

        self._build_updated = True

    def _build_dtso(self, rule):
        self._log('dtc', rule.target)
        out_path = self._path / rule.output
        if out_path.exists():
            raise RuntimeError(
                f'duplicate overlay name detected: {rule.output}')

        with open(out_path, 'wb') as out:
            cpp = subprocess.Popen(['cpp', *self._cpp_flags, rule.target],
                                   stdout=subprocess.PIPE)
            dts = subprocess.Popen(['dtc', '-I', 'dts', '-O', 'dtb'],
                                   stdin=cpp.stdout, stdout=out)
            cpp.stdout.close()
            if dts.wait():
                sys.exit(1)

    def check(self):
        shutil.copyfile(self._dt.path, self._local_check)

        for rule in self._src.get_active_rules(self._local_cfg):
            if isinstance(rule, DtsoRule):
                self._log('check', rule.output)
                self._overlay_dtbo(self._local_check, self._path / rule.output)

        check_dt = DeviceTree(self._local_check)
        return self._check_pins(check_dt)

    def _check_pins(self, check_dt):
        pinmap = {}
        symbols = {}
        names = {}
        for dtb, node, props in check_dt.walk():
            if node == '/__symbols__':
                symbols = {v.as_str(): k for k, v in props.items()}
                continue
            if 'status' in props and props['status'] != b'okay\0':
                continue
            for k in props:
                if not k.startswith('pinctrl-'):
                    continue
                if k == 'pinctrl-names':
                    names[node] = {
                        f'pinctrl-{i}': s
                        for i, s in enumerate(props[k].as_stringlist())
                    }
                    continue
                for phandle in props[k].as_list('I'):
                    node_off = dtb.node_offset_by_phandle(phandle)
                    self._check_pinctrl(
                        check_dt, dtb, node_off, pinmap, node, k)

        success = True
        for pin, users in pinmap.items():
            # only one user is always fine
            if len(users) == 1:
                continue

            # more than one user is fine as long as
            # * all of them are the same node
            # * all of them are distinct properties
            first_user, first_prop, _ = users[0]
            if all(u[0] == first_user and u[1] != first_prop
                   for u in users[1:]):
                continue

            success = False

            rmio = None
            name = pin
            if pin in self._RMIO:
                rmio = self._RMIO.index(pin)
                name = f'{rmio} ({pin})'

            print('', file=sys.stderr)
            print(f'ERROR: pin {name} is used more than once:',
                  file=sys.stderr)
            for (user, prop, pinctrl) in users:
                pinctrl_name = names.get(user, {}).get(prop)
                pinctrl_name = f' ({pinctrl_name!r})'
                if user in symbols:
                    user = '&' + symbols[user]
                print(f'  {user:20s} {prop}{pinctrl_name} {pinctrl}',
                      file=sys.stderr)

        return success

    def _check_pinctrl(self, check_dt, dtb, node_off, pinmap, user, user_prop):
        for dtb, node, props in check_dt.walk_node(dtb, node_off):
            if 'rockchip,pins' not in props:
                raise RuntimeError(f'pinctrl with no pins: {node}')
            pins = props['rockchip,pins'].as_list('I')
            if not len(pins) % 4 == 0:
                raise RuntimeError(f'pinctrl with bad format: {node}')
            for i in range(0, len(pins), 4):
                pin = pins[i:i + 4]

                bank = pin[0]
                letter = chr(ord('A') + pin[1] // 8)
                number = pin[1] % 8
                name = f'GPIO{bank}_{letter}{number}'
                # function = pin[2]
                # config = pin[3]

                pinmap.setdefault(name, []).append((user, user_prop, node))

    def _overlay_dtbo(self, dtb, overlay):
        try:
            subprocess.run(['fdtoverlay', '-i', dtb, '-o', dtb, overlay],
                           check=True)
        except subprocess.CalledProcessError:
            sys.exit(1)

    def _install_with_header(self, header, src_path, dest_path):
        with open(src_path) as src:
            with open(dest_path, 'w') as dest:
                for line in header.splitlines():
                    line = f'# {line.strip()}'
                    print(line, file=dest)
                print('', file=dest)
                shutil.copyfileobj(src, dest)

    def install_build_check_permissions(self):
        if not self._out.is_writeable():
            return [self._out.path]
        return []

    def install_build(self):
        if not self._build_updated:
            return

        for p in self._out.path.glob('*.dtbo'):
            self._log('rm', p)
            p.unlink()

        for rule in self._src.get_active_rules(self._local_cfg):
            if isinstance(rule, DtsoRule):
                in_path = self._path / rule.output
                out_path = self._out.path / rule.output
                self._log('install', out_path)
                shutil.copyfile(in_path, out_path)

        self._log('install', self._backup_cfg)
        self._install_with_header(
            self._CONFIG_BACKUP_HEADER, self._local_cfg, self._backup_cfg)

        self._log('install', self._output_readme)
        with open(self._output_readme, 'w') as out:
            for line in self._OUTPUT_README.splitlines():
                line = line.strip()
                print(line, file=out)

    def install_config_check_permissions(self):
        if not self._cfg.is_writeable():
            return [self._cfg.path]
        return []

    def install_config(self):
        if not self._cfg_updated:
            return

        self._log('install', self._cfg.path)
        self._install_with_header(
            self._CONFIG_INSTALL_HEADER, self._local_cfg, self._cfg.path)
